version: '3'
services:
  react-app:
    build: .
    container_name: online-marketplace
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Required for hot reloading in some environments